from pymclevel import MCSchematic
from pymclevel.nbt import *
from pymclevel.box import Vector
# TODO: rename your function
def createSchematic():
    e = MCSchematic(shape=(8,2,7),filename='')
    e._Blocks = [[[137,0,137,137,137,137,137,137],[137,0,137,137,137,137,137,137],[137,159,137,137,137,137,137,137],[137,0,137,137,137,137,137,137],[0,0,0,137,137,137,137,137],[0,0,0,137,137,137,137,137],[0,0,0,137,137,137,137,137]],[[55,0,55,55,55,55,55,55],[55,0,55,55,55,55,55,55],[55,55,55,55,55,55,55,55],[55,0,55,55,55,55,55,55],[0,0,0,55,55,55,55,55],[0,0,0,55,55,55,55,55],[0,0,0,55,55,55,55,55]]]
    e.root_tag['TileEntities'] = TAG_List([
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,85f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(0),
    "y": TAG_Int(0),
    "z": TAG_Int(1),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,280f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(3),
    "y": TAG_Int(0),
    "z": TAG_Int(1),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,350f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(2),
    "y": TAG_Int(0),
    "z": TAG_Int(1),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,140f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(5),
    "y": TAG_Int(0),
    "z": TAG_Int(1),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,250f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(4),
    "y": TAG_Int(0),
    "z": TAG_Int(1),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,10f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(7),
    "y": TAG_Int(0),
    "z": TAG_Int(1),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,110f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(6),
    "y": TAG_Int(0),
    "z": TAG_Int(1),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,130f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(5),
    "y": TAG_Int(0),
    "z": TAG_Int(0),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,120f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(6),
    "y": TAG_Int(0),
    "z": TAG_Int(0),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,270f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(3),
    "y": TAG_Int(0),
    "z": TAG_Int(0),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,260f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(4),
    "y": TAG_Int(0),
    "z": TAG_Int(0),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,0f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(7),
    "y": TAG_Int(0),
    "z": TAG_Int(0),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,340f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(2),
    "y": TAG_Int(0),
    "z": TAG_Int(0),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,-5f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(0),
    "y": TAG_Int(0),
    "z": TAG_Int(0),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,70f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(6),
    "y": TAG_Int(0),
    "z": TAG_Int(5),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,50f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(7),
    "y": TAG_Int(0),
    "z": TAG_Int(5),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,310f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(3),
    "y": TAG_Int(0),
    "z": TAG_Int(4),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,220f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(4),
    "y": TAG_Int(0),
    "z": TAG_Int(4),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,170f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(5),
    "y": TAG_Int(0),
    "z": TAG_Int(4),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,80f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(6),
    "y": TAG_Int(0),
    "z": TAG_Int(4),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,100f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(6),
    "y": TAG_Int(0),
    "z": TAG_Int(2),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,265f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(0),
    "y": TAG_Int(0),
    "z": TAG_Int(3),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,150f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(5),
    "y": TAG_Int(0),
    "z": TAG_Int(2),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,360f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(2),
    "y": TAG_Int(0),
    "z": TAG_Int(3),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,300f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(3),
    "y": TAG_Int(0),
    "z": TAG_Int(3),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,20f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(7),
    "y": TAG_Int(0),
    "z": TAG_Int(2),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,360f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(2),
    "y": TAG_Int(0),
    "z": TAG_Int(2),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,230f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(4),
    "y": TAG_Int(0),
    "z": TAG_Int(3),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,160f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(5),
    "y": TAG_Int(0),
    "z": TAG_Int(3),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,40f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(7),
    "y": TAG_Int(0),
    "z": TAG_Int(4),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,240f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(4),
    "y": TAG_Int(0),
    "z": TAG_Int(2),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,90f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(6),
    "y": TAG_Int(0),
    "z": TAG_Int(3),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,30f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(7),
    "y": TAG_Int(0),
    "z": TAG_Int(3),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,290f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(3),
    "y": TAG_Int(0),
    "z": TAG_Int(2),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,175f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(0),
    "y": TAG_Int(0),
    "z": TAG_Int(2),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,180f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(5),
    "y": TAG_Int(0),
    "z": TAG_Int(5),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,210f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(4),
    "y": TAG_Int(0),
    "z": TAG_Int(5),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,320f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(3),
    "y": TAG_Int(0),
    "z": TAG_Int(5),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,330f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(3),
    "y": TAG_Int(0),
    "z": TAG_Int(6),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,200f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(4),
    "y": TAG_Int(0),
    "z": TAG_Int(6),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,50f]}s'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.tagError","with":["Unable to locate ending bracket for: {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,50f]}s"]}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(7),
    "y": TAG_Int(0),
    "z": TAG_Int(6),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,60f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(6),
    "y": TAG_Int(0),
    "z": TAG_Int(6),
  }),
  TAG_Compound({
    "Command": TAG_String(u'/summon MinecartRideable 0 36 0 {CustomDisplayTile:1,DisplayTile:159,DisplayData:4,DisplayOffset:84,Rotation:[90f,190f]}'),
    "id": TAG_String(u'Control'),
    "TrackOutput": TAG_Byte(1),
    "LastOutput": TAG_String(u'{"extra":[{"translate":"commands.summon.success"}],"text":"[18:12:58] "}'),
    "CustomName": TAG_String(u'@'),
    "SuccessCount": TAG_Int(1),
    "x": TAG_Int(5),
    "y": TAG_Int(0),
    "z": TAG_Int(6),
  }),
])
    e.root_tag['Data'] = TAG_Byte_Array([[[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,5,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0]],[[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0]]])
    return e

lamp = createSchematic()
def placelamp(level, dest):
    vec = Vector(0,1,0)

    level.copyBlocksFrom(lamp,lamp.bounds,vec + dest)

def perform(level, box, options):
    placelamp(level,[box.minx,box.miny,box.minz])
    level.markDirtyBox = True
    
